### ISSUE TITLE
Handling of changes in the list

### ISSUE THREAD

**Issue by rob2022** [vijay-rhaud/todo-app#1]
https://github.com/vijay-rhaud/todo-app/blob/6f7872f386960e688abe0e85173131f303108133/src/components/TodoList.vue#L16

Not sure if this is a work in progress or if you'r stuck on it, either way look at the approach you took in `UserInput` i.e emitting a change from the child to the parent and try and replicate it here. 

side note...... document.getElementById is not a good solution in vue we generally dont select elements from the dom and if we do we do it via refs (https://blog.logrocket.com/how-to-use-refs-to-access-your-application-dom-in-vue-js/) but you dont need to do that here.

(what you'r doing now is probable the hardest part of vue so dont sweet it :) )

**Comment by vijay-rhaud** [comment]
This was a WIP, not finished with this page yet👍🏾
